import type { Provenance, Source } from '@/domain/types';

/**
 * Every catalog record in this build ships as demo data. It is realistic and
 * internally consistent, but it is NOT a factual claim about any institution
 * or programme, and the UI says so wherever it is shown.
 *
 * When the admin content system (or a real data feed) replaces a record, the
 * provenance flips to `verified` and carries a source plus a verification date.
 */
export const DEMO_NOTE =
  'Demo data for development. Not verified against the institution. Check the official site before relying on it.';

export function demo(sources: Source[] = [], note = DEMO_NOTE): Provenance {
  return { kind: 'demo', sources, note };
}

/** Structure we are confident about but have not checked against the publisher. */
export function unverified(sources: Source[], note?: string): Provenance {
  return {
    kind: 'unverified',
    sources,
    note:
      note ??
      'Structure summarised from public course descriptions and not re-checked against the official source this cycle. Confirm current details with the publisher.',
  };
}

export function verified(sources: Source[], lastVerified: string, note?: string): Provenance {
  return { kind: 'verified', sources, lastVerified, note };
}

export function aiGenerated(note = 'Generated by Pathway AI from your profile. Guidance, not fact.'): Provenance {
  return { kind: 'ai', note };
}

export function userEntered(note = 'Entered by you.'): Provenance {
  return { kind: 'user', note };
}

/* --- Frequently referenced publishers ----------------------------------- */
export const SRC = {
  collegeBoardAP: {
    label: 'AP Courses & Exams',
    url: 'https://apstudents.collegeboard.org/course-index-page',
    publisher: 'College Board',
  },
  collegeBoardSAT: {
    label: 'About the SAT',
    url: 'https://satsuite.collegeboard.org/sat',
    publisher: 'College Board',
  },
  collegeBoardAPCED: {
    label: 'AP Course and Exam Descriptions',
    url: 'https://apcentral.collegeboard.org/courses',
    publisher: 'College Board',
  },
  scorecard: {
    label: 'College Scorecard',
    url: 'https://collegescorecard.ed.gov/',
    publisher: 'U.S. Department of Education',
  },
  ipeds: {
    label: 'IPEDS Data Center',
    url: 'https://nces.ed.gov/ipeds/',
    publisher: 'National Center for Education Statistics',
  },
  commonApp: {
    label: 'Common App member requirements',
    url: 'https://www.commonapp.org/explore',
    publisher: 'Common Application',
  },
  fafsa: {
    label: 'Federal Student Aid',
    url: 'https://studentaid.gov/',
    publisher: 'U.S. Department of Education',
  },
  netPrice: {
    label: 'Net Price Calculator Center',
    url: 'https://collegecost.ed.gov/net-price',
    publisher: 'U.S. Department of Education',
  },
} satisfies Record<string, Source>;

export function provenanceLabel(p: Provenance): string {
  switch (p.kind) {
    case 'verified':
      return p.lastVerified ? `Verified ${p.lastVerified}` : 'Verified';
    case 'ai':
      return 'AI guidance';
    case 'user':
      return 'You entered this';
    case 'demo':
      return 'Demo data';
    default:
      return 'Unverified';
  }
}
