import { c, u, apBands, course } from './kit.js';

export default course({
  key: 'ap-biology',
  title: 'AP Biology',
  exam: 'AP Biology',
  subject: 'Biology',
  level: 'AP / first-year college',
  aliases: ['ap biology', 'ap bio'],
  overview:
    'Eight units built on four big ideas: evolution, energetics, information storage and transmission, and systems interactions. The exam is an experiment-and-data exam more than a recall exam — half the marks are free response, and the two long questions are almost entirely about interpreting an experiment you have never seen. Statistics, controls, and the ability to justify a claim with evidence carry more marks than vocabulary.',
  total_hours: 170,
  exam_format: {
    total_minutes: 180,
    description:
      'Section I is 60 multiple-choice questions in 90 minutes, worth 50%. Section II is 6 free-response questions in 90 minutes, worth 50%: two long questions (interpreting and evaluating experimental results, one of them with graphing) and four short questions covering scientific investigation, conceptual analysis, visual representations and data analysis. A four-function calculator and the formula sheet, including chi-square and standard error, are allowed.',
    sections: [
      { name: 'Section I: Multiple Choice', question_type: 'mcq', count: 60, minutes: 90, weight_percent: 50, notes: 'Heavy on data sets, graphs and short experimental scenarios rather than isolated recall.' },
      { name: 'Section II: Free Response', question_type: 'frq', count: 6, minutes: 90, weight_percent: 50, notes: 'Questions 1 and 2 are long (8-10 points each). Marks come from identifying variables and controls, justifying predictions, and connecting a result to a mechanism.' },
    ],
  },
  score_bands: apBands([72, 59, 44, 29]),
  units: [
    u(1, 'Chemistry of Life', [8, 11], 14,
      'Water, macromolecules and the chemical properties that make biological structure possible.',
      [
        c('Properties of water', 2, 'core'),
        c('Hydrogen bonding and polarity', 2, 'core'),
        c('Carbon skeletons and functional groups', 2, 'core'),
        c('Monomers, polymers and dehydration synthesis', 3, 'core'),
        c('Carbohydrate structure and function', 2, 'core'),
        c('Lipid structure and function', 3, 'core'),
        c('Protein structure levels', 4, 'core', ['Monomers, polymers and dehydration synthesis']),
        c('Nucleic acid structure', 3, 'core'),
        c('Directionality of biological polymers', 3, 'important', ['Nucleic acid structure']),
      ],
      [
        ['Describing a protein\'s function without reference to its shape.', 'Function follows from tertiary structure; almost every AP answer about a protein should route through shape.'],
      ]),
    u(2, 'Cell Structure and Function', [10, 13], 18,
      'Organelles, membranes, transport and the surface-area-to-volume constraint that shapes cells.',
      [
        c('Cell organelles and their functions', 2, 'core'),
        c('Prokaryotic versus eukaryotic cells', 2, 'core'),
        c('Endosymbiotic theory', 3, 'core'),
        c('Surface area to volume ratio', 3, 'core'),
        c('Fluid mosaic membrane model', 3, 'core'),
        c('Passive transport and diffusion', 3, 'core', ['Fluid mosaic membrane model']),
        c('Osmosis and water potential', 4, 'core', ['Passive transport and diffusion']),
        c('Active transport and pumps', 3, 'core', ['Fluid mosaic membrane model']),
        c('Tonicity and cell responses', 4, 'core', ['Osmosis and water potential']),
        c('Compartmentalisation', 3, 'important'),
      ],
      [
        ['Getting the sign of water potential backwards.', 'Water moves from higher (less negative) to lower (more negative) water potential. Solute potential is always negative.'],
        ['Saying a hypertonic solution makes a cell swell.', 'Hypertonic means more solute outside, so water leaves and the cell shrinks.'],
      ]),
    u(3, 'Cellular Energetics', [12, 16], 22,
      'Enzymes, and the two energy-converting pathways: photosynthesis and cellular respiration.',
      [
        c('Enzyme structure and active site', 3, 'core', ['Protein structure levels']),
        c('Enzyme kinetics and reaction rate', 4, 'core', ['Enzyme structure and active site']),
        c('Enzyme inhibition', 4, 'core', ['Enzyme kinetics and reaction rate']),
        c('Environmental effects on enzyme function', 3, 'core', ['Enzyme structure and active site']),
        c('Cellular energy and ATP', 2, 'core'),
        c('Glycolysis', 3, 'core'),
        c('Krebs cycle', 4, 'core', ['Glycolysis']),
        c('Oxidative phosphorylation and chemiosmosis', 4, 'core', ['Krebs cycle']),
        c('Anaerobic respiration and fermentation', 3, 'core', ['Glycolysis']),
        c('Light-dependent reactions', 4, 'core'),
        c('Calvin cycle', 4, 'core', ['Light-dependent reactions']),
        c('Photosynthesis and respiration as coupled cycles', 4, 'important', ['Calvin cycle', 'Oxidative phosphorylation and chemiosmosis']),
      ],
      [
        ['Reciting pathway steps rather than tracing energy and electrons.', 'The exam asks what happens to the proton gradient or the electron carriers when something is blocked. Learn the flow, not the list.'],
        ['Treating a competitive inhibitor as un-outcompetable.', 'Competitive inhibition can be overcome by raising substrate concentration; non-competitive cannot.'],
      ]),
    u(4, 'Cell Communication and Cell Cycle', [10, 15], 18,
      'Signal transduction, feedback, and the regulated cell cycle.',
      [
        c('Cell signalling types', 2, 'core'),
        c('Signal transduction pathways', 4, 'core', ['Cell signalling types']),
        c('Signal amplification', 4, 'important', ['Signal transduction pathways']),
        c('Negative and positive feedback', 3, 'core'),
        c('Homeostasis', 3, 'core', ['Negative and positive feedback']),
        c('Phases of the cell cycle', 2, 'core'),
        c('Mitosis', 3, 'core', ['Phases of the cell cycle']),
        c('Cell cycle checkpoints and regulation', 4, 'core', ['Phases of the cell cycle']),
        c('Cancer as loss of cell cycle control', 3, 'important', ['Cell cycle checkpoints and regulation']),
      ],
      [
        ['Calling any amplifying loop positive feedback.', 'Positive feedback pushes further from the set point; negative feedback returns toward it, even when the response is large.'],
      ]),
    u(5, 'Heredity', [8, 11], 14,
      'Meiosis, Mendelian inheritance and the sources of genetic variation.',
      [
        c('Meiosis', 3, 'core', ['Mitosis']),
        c('Crossing over and independent assortment', 4, 'core', ['Meiosis']),
        c('Mendelian genetics and Punnett squares', 3, 'core'),
        c('Probability rules in genetics', 3, 'core', ['Mendelian genetics and Punnett squares']),
        c('Non-Mendelian inheritance', 4, 'core', ['Mendelian genetics and Punnett squares']),
        c('Sex-linked inheritance', 4, 'core', ['Mendelian genetics and Punnett squares']),
        c('Pedigree analysis', 4, 'core', ['Sex-linked inheritance']),
        c('Chi-square test for genetic data', 4, 'core', ['Probability rules in genetics']),
        c('Environmental effects on phenotype', 2, 'important'),
      ],
      [
        ['Reporting a chi-square value without stating degrees of freedom and the conclusion.', 'Marks come from comparing to the critical value and saying whether the null hypothesis is rejected, in context.'],
      ]),
    u(6, 'Gene Expression and Regulation', [12, 16], 22,
      'From DNA to protein, how expression is controlled, and the biotechnology built on it.',
      [
        c('DNA and RNA structure', 3, 'core', ['Nucleic acid structure']),
        c('DNA replication', 4, 'core', ['DNA and RNA structure']),
        c('Transcription', 4, 'core', ['DNA and RNA structure']),
        c('RNA processing in eukaryotes', 4, 'core', ['Transcription']),
        c('Translation', 4, 'core', ['Transcription']),
        c('The genetic code and reading frames', 3, 'core', ['Translation']),
        c('Operons and prokaryotic gene regulation', 4, 'core', ['Transcription']),
        c('Eukaryotic gene regulation', 4, 'core', ['Transcription']),
        c('Types of mutations and their effects', 4, 'core', ['The genetic code and reading frames']),
        c('Gel electrophoresis and PCR', 3, 'important'),
        c('Genetic engineering and transformation', 3, 'important'),
      ],
      [
        ['Assuming a point mutation always changes the protein.', 'The code is redundant; a silent mutation changes the codon but not the amino acid. Frameshifts, by contrast, usually wreck everything downstream.'],
        ['Mixing up the lac and trp operons.', 'lac is inducible and catabolic; trp is repressible and anabolic. Ask what the cell gains by switching it on.'],
      ]),
    u(7, 'Natural Selection', [13, 20], 24,
      'Evolution as the central explanatory idea: selection, drift, speciation, phylogeny and the evidence for common ancestry.',
      [
        c('Natural selection', 3, 'core'),
        c('Fitness and differential reproduction', 3, 'core', ['Natural selection']),
        c('Types of selection', 3, 'core', ['Natural selection']),
        c('Genetic drift and bottleneck effects', 3, 'core'),
        c('Gene flow', 2, 'core'),
        c('Hardy-Weinberg equilibrium', 4, 'core', ['Probability rules in genetics']),
        c('Conditions for Hardy-Weinberg', 4, 'core', ['Hardy-Weinberg equilibrium']),
        c('Speciation and reproductive isolation', 4, 'core'),
        c('Phylogenetic trees and cladograms', 4, 'core'),
        c('Evidence for common ancestry', 3, 'core'),
        c('Origin of life hypotheses', 2, 'peripheral'),
      ],
      [
        ['Saying a population "adapted in order to" survive.', 'Selection acts on existing variation; individuals do not acquire traits because they are needed. Phrase it as differential survival and reproduction.'],
        ['Using Hardy-Weinberg without checking its assumptions.', 'A question that says the population is evolving is telling you the equilibrium does not hold — and usually asking which condition is violated.'],
      ]),
    u(8, 'Ecology', [10, 15], 18,
      'Behaviour, populations, communities, ecosystems and how disruption propagates through them.',
      [
        c('Animal behaviour and communication', 2, 'core'),
        c('Energy flow and trophic levels', 3, 'core'),
        c('Ten percent rule and energy loss', 3, 'core', ['Energy flow and trophic levels']),
        c('Population growth models', 4, 'core'),
        c('Carrying capacity and limiting factors', 3, 'core', ['Population growth models']),
        c('Community interactions', 3, 'core'),
        c('Species diversity and Simpson index', 3, 'important'),
        c('Ecological succession', 2, 'important'),
        c('Biogeochemical cycles', 3, 'important'),
        c('Human impact and invasive species', 3, 'important'),
      ],
      [
        ['Answering a disruption question with one step.', 'Marks come from following the chain: what changes, what that does to the next trophic level, and what that does to the one after.'],
      ]),
  ],
});
