"""Real destination for every venue type: the organisation itself, or the
official national directory whose entire job is to hand you the local contact.

These replace search-engine links. Every URL below is a government site or a
major national association -- the most stable addresses available -- chosen as
top-level pages rather than deep paths, because deep paths rot.

NOTE ON VERIFICATION: this session's network egress is restricted to GitHub, so
none of these were fetched to confirm they still resolve. They are recorded from
knowledge, not checked. If one has moved, fix it here and rerun build.py.
"""

# venue key -> (label, official finder URL, what that page is, what to do there)
FINDERS = {
"library": ("Public library directory", "https://www.publiclibraries.com/",
  "A state-by-state directory of United States public library systems.",
  "Pick your state, find your local system, then look for Youth Services or Programming."),

"elem": ("NCES Public School Search", "https://nces.ed.gov/ccd/schoolsearch/",
  "The federal government's searchable database of every public school in the country.",
  "Search by city or ZIP, then call the front office and ask for the STEM or science lead."),
"middle": ("NCES Public School Search", "https://nces.ed.gov/ccd/schoolsearch/",
  "The federal government's searchable database of every public school in the country.",
  "Filter to middle schools in your district, then email the science department chair."),
"highschool": ("NCES Public School Search", "https://nces.ed.gov/ccd/schoolsearch/",
  "The federal government's searchable database of every public school in the country.",
  "Look for high schools near you with no robotics team, then contact the CTE coordinator."),
"title1": ("NCES Public School Search", "https://nces.ed.gov/ccd/schoolsearch/",
  "Federal school database; it reports Title I status for every school.",
  "Filter to Title I schools, then ask the district's federal programs office who to talk to."),
"rural": ("NCES Public School Search", "https://nces.ed.gov/ccd/schoolsearch/",
  "Federal school database with a locale filter that identifies rural districts.",
  "Set locale to Rural, then email the superintendent -- small districts answer directly."),
"bilingual": ("NCES Public School Search", "https://nces.ed.gov/ccd/schoolsearch/",
  "Federal school database covering every public school including dual-language programs.",
  "Find schools in your area, then ask the district for the bilingual programs coordinator."),

"museum": ("Association of Science and Technology Centers", "https://www.astc.org/",
  "The trade association for science centres and museums, with a member directory.",
  "Find your nearest member centre, then contact Public Programs about a demo slot."),
"cc": ("AACC community college finder", "https://www.aacc.nche.edu/",
  "The American Association of Community Colleges, which lists member colleges.",
  "Find colleges near you, then contact their STEM outreach or dual-enrolment office."),
"univ": ("College Navigator", "https://nces.ed.gov/collegenavigator/",
  "The federal college search tool; filter by state, distance and programme.",
  "Filter to engineering programmes near you, then look for the K-12 Outreach office."),

"bgc": ("Boys & Girls Clubs of America", "https://www.bgca.org/",
  "The national body; the site has a find-a-club tool covering every local club.",
  "Find your nearest club and email its Program Director -- clubs decide locally."),
"ymca": ("YMCA locator", "https://www.ymca.org/",
  "The national YMCA site, with a locator for every branch.",
  "Find your branch, then ask for the Youth Development Director."),
"gs": ("Girl Scouts council finder", "https://www.girlscouts.org/",
  "The national Girl Scouts site, which routes you to your regional council.",
  "Enter your ZIP to reach your council, then contact their Program department."),
"scouts": ("BeAScout unit finder", "https://beascout.scouting.org/",
  "Scouting America's official tool for finding troops and packs near you.",
  "Find local units, then contact the Scoutmaster about the Robotics merit badge."),
"fourh": ("4-H county finder", "https://4-h.org/",
  "The national 4-H site, which routes you to your county extension office.",
  "Find your county office and email the 4-H Youth Development Agent."),
"afterschool": ("Afterschool Alliance", "https://afterschoolalliance.org/",
  "The national body for after-school programmes, with state networks listed.",
  "Find your state network, then ask which local sites want STEM programming."),
"camp": ("American Camp Association camp finder", "https://find.acacamps.org/",
  "The ACA's searchable database of accredited camps.",
  "Search your area, then contact camp directors in autumn -- summer is planned early."),

"hospital": ("Children's Hospital Association", "https://www.childrenshospitals.org/",
  "The national association of children's hospitals, with a member directory.",
  "Find your nearest children's hospital, then ask for Child Life Services."),
"sped": ("Parent Center Hub", "https://www.parentcenterhub.org/find-your-center/",
  "The federally funded network of parent centres for families of children with disabilities.",
  "Your state's centre knows every special-education programme locally and will point you."),
"dhh": ("American Printing House", "https://www.aph.org/",
  "A national organisation serving students who are blind or have low vision.",
  "Use it to reach state schools and outreach coordinators for sensory-disability programmes."),
"shelterfam": ("211", "https://www.211.org/",
  "The national referral service connecting people to local health and human services.",
  "Search your area for family shelters and transitional housing, then ask for Family Services."),
"housing": ("HUD public housing agency contacts", "https://www.hud.gov/program_offices/public_indian_housing/pha/contacts",
  "HUD's official contact list for every public housing authority in the country.",
  "Find your local authority and ask for Resident Services -- they run the community centres."),
"juvenile": ("OJJDP", "https://ojjdp.ojp.gov/",
  "The federal office for juvenile justice, which lists state agencies.",
  "Work through your state agency; education programmes inside facilities are not walk-in."),
"tribal": ("Bureau of Indian Education", "https://www.bie.edu/",
  "The federal agency for schools serving Native American communities.",
  "Find schools in your region, then contact the Education Director -- expect a long lead time."),
"military": ("Military OneSource", "https://www.militaryonesource.mil/",
  "The Department of Defense's family support portal, including School Liaison contacts.",
  "Find the School Liaison Officer for the installation near you -- that is the right door."),
"refugee": ("Office of Refugee Resettlement", "https://www.acf.hhs.gov/orr",
  "The federal office that funds refugee services, with state programme listings.",
  "Find your state programme, then ask which local agencies run youth or ESL programming."),
"senior": ("Eldercare Locator", "https://eldercare.acl.gov/",
  "The federal service for finding senior centres and area agencies on ageing.",
  "Search your ZIP for senior centres, then ask for the Activities Director."),

"parks": ("National Recreation and Park Association", "https://www.nrpa.org/",
  "The national body for parks and recreation departments.",
  "Use it to reach your city or county department's recreation programme coordinator."),
"city": ("USA.gov local governments", "https://www.usa.gov/local-governments",
  "The official routing page to every city and county government in the country.",
  "Find your city site, then contact constituent services about events and proclamations."),
"chamber": ("U.S. Chamber of Commerce", "https://www.uschamber.com/",
  "The national chamber, which routes to local and state chambers.",
  "Find your local chamber, then ask about their events calendar and member breakfasts."),
"rotary": ("Rotary club finder", "https://www.rotary.org/en/search/club-finder",
  "Rotary International's official tool for finding clubs and meeting times.",
  "Clubs need speakers weekly. Kiwanis and Lions run their own finders the same way."),
"manuf": ("MEP National Network", "https://www.nist.gov/mep",
  "The federal network of manufacturing extension centres, one per state.",
  "Your state centre knows every local manufacturer and can introduce you."),
"tech": ("FIRST sponsorship", "https://www.firstinspires.org/ways-to-help/sponsor",
  "FIRST's own page on how companies sponsor teams, with the case already made for you.",
  "Send this page to a company's community relations contact so they see the programme."),
"faith": ("JustServe", "https://www.justserve.org/",
  "A free directory of local community and faith-based service projects.",
  "Search your area for youth-serving organisations that already want volunteers."),
"homeschool": ("HSLDA state groups", "https://hslda.org/",
  "The national homeschool organisation, which lists state and regional groups.",
  "State groups run co-ops and will circulate an offer of a free robotics session."),
"media": ("NPR station finder", "https://www.npr.org/stations/",
  "The official directory of public radio stations by location.",
  "Local public radio and TV cover student engineering stories; pitch the assignment desk."),

"foodbank": ("Feeding America food bank locator", "https://www.feedingamerica.org/find-your-local-foodbank",
  "The official locator for every member food bank in the country.",
  "Find your food bank, then register your group with their volunteer coordinator."),
"shelter": ("Petfinder shelter search", "https://www.petfinder.com/animal-shelters-and-rescues/search/",
  "A searchable directory of animal shelters and rescues by location.",
  "Find shelters near you and ask their volunteer manager about group shifts."),
"habitat": ("Habitat for Humanity affiliate finder", "https://www.habitat.org/",
  "The national site, which routes you to your local affiliate.",
  "Check the age minimum before recruiting -- ReStore usually takes younger volunteers."),

"maker": ("Maker Faire", "https://makerfaire.com/",
  "The network of maker events, which lists regional faires and maker communities.",
  "Regional faires accept Maker applications free; makerspaces are listed through them."),
"fair": ("International Association of Fairs and Expositions", "https://www.fairsandexpos.com/",
  "The trade body for county and state fairs, with a member directory.",
  "Find your fair, then contact the exhibits coordinator -- booths are booked months ahead."),
"market": ("USDA farmers market directory", "https://www.ams.usda.gov/local-food-directories/farmersmarkets",
  "The federal government's official directory of farmers markets.",
  "Search by state, then email the market manager about a demo table."),

"fll": ("FIRST team and event search", "https://www.firstinspires.org/team-event-search",
  "FIRST's own tool for finding every registered team and event near you.",
  "Search your area for FLL and FTC teams -- rookie teams there need technical mentors."),
"event": ("FIRST team and event search", "https://www.firstinspires.org/team-event-search",
  "FIRST's own tool listing every official event, with volunteer links.",
  "Find events near you, then register through the volunteer portal 4-6 weeks ahead."),
}


# Most of the directories above are United States federal or national bodies and
# are useless outside the country. These are the ones that genuinely work
# worldwide; a venue type absent here simply produces no rows outside the US.
GLOBAL = {
"fll": ("FIRST team and event search", "https://www.firstinspires.org/team-event-search",
  "FIRST's own tool for finding registered teams and events, worldwide.",
  "Search your country for FLL and FTC teams -- rookie teams need technical mentors everywhere."),
"event": ("FIRST team and event search", "https://www.firstinspires.org/team-event-search",
  "FIRST's own tool listing official events in every country it operates in.",
  "Find events near you, then register through the volunteer portal 4-6 weeks ahead."),
"museum": ("Association of Science and Technology Centers", "https://www.astc.org/",
  "ASTC's membership is international; the directory covers science centres worldwide.",
  "Find your nearest member centre, then contact its public programmes team."),
"rotary": ("Rotary club finder", "https://www.rotary.org/en/search/club-finder",
  "Rotary International operates in most countries and the club finder is global.",
  "Clubs need speakers every week and will host a student presentation readily."),
"habitat": ("Habitat for Humanity", "https://www.habitat.org/",
  "Habitat runs national organisations in over seventy countries.",
  "Find your national organisation, then ask about group volunteering age rules."),
"maker": ("Maker Faire", "https://makerfaire.com/",
  "Maker Faires run worldwide and list regional events and maker communities.",
  "Apply to your regional faire as a Maker -- those booths are normally free."),
"scouts": ("World Organization of the Scout Movement", "https://www.scout.org/",
  "The global scouting body, which routes to the national association in your country.",
  "Find your national association, then contact a local group about STEM badges."),
"univ": ("FIRST team and event search", "https://www.firstinspires.org/team-event-search",
  "Universities that host FIRST events are listed here with their contacts.",
  "Find a nearby host university, then ask who runs their outreach programme."),
}
