"""Real, nationally-operating organizations and programs that take robotics-team
outreach. URLs are organization homepages (stable) rather than deep links (which
rot). Dates are recurring annual windows, not specific-year deadlines.

Every entry here still needs one confirmation call or email before you commit to
a date. "Verified" means the organization is real and this is genuinely how they
work with teams -- not that a slot is being held for you.
"""

# name, program, url, category, audience, format, season, window, deadline,
# how to apply, what to ask for, hours, reach, effort, impact, notes, tags
VERIFIED = [
 ("FIRST", "Volunteer at an official FIRST event", "https://www.firstinspires.org",
  "Volunteering", "All ages", "In person", "Competition", "Regional and district events run January-April",
  "Register 4-6 weeks before the event; popular roles fill first",
  "Portal", "Create a FIRST account, complete youth-protection screening, then apply to specific event roles",
  10, 250, "Low", 4,
  "The single highest-yield thing an outreach lead can schedule. Judge Advisor, Queuing, Field Reset and Pit Admin all take students where local rules allow.",
  ["FIRST","competition","recurring"]),

 ("FIRST", "National Robotics Week events", "https://www.nationalroboticsweek.org",
  "Demo", "All ages", "In person", "Offseason", "First full week of April, every year",
  "List your own event 4-8 weeks ahead; attend anything nearby with no lead time",
  "Web form", "Register your event on the National Robotics Week site, then invite local press",
  16, 300, "Medium", 4,
  "You can both attend listed events and register your own. Registering yours puts your team on a national map, which reads well in an Impact Award submission.",
  ["FIRST","recurring","april"]),

 ("FIRST", "FIRST LEGO League volunteer and coach roles", "https://www.firstinspires.org",
  "Mentoring", "Elementary (K-5)", "Hybrid", "Fall", "Season runs August-February; qualifiers November-January",
  "Coaches commit by September; event volunteers 4 weeks out",
  "Portal", "Contact your FIRST Program Delivery Partner (listed by state on the FIRST site)",
  24, 15, "High", 5,
  "Your Program Delivery Partner is the person who knows which local FLL teams have no coach. One email to them beats twenty cold emails to schools.",
  ["FIRST","FLL","mentoring"]),

 ("NASA", "NASA STEM Engagement", "https://www.nasa.gov/learning-resources/",
  "Workshop", "All ages", "Hybrid", "Offseason", "Year-round; NASA STEM Day events cluster in spring",
  "Rolling; some challenges have fixed fall deadlines",
  "Web form", "Browse STEM engagement programs and request materials or a speaker through the site",
  8, 80, "Low", 4,
  "Free, high-quality lesson materials you can run at a library or school without writing curriculum yourself. Speaker requests take longer than you think.",
  ["national","free-materials"]),

 ("Code.org", "Hour of Code", "https://hourofcode.com",
  "Workshop", "Elementary (K-5)", "Hybrid", "Winter", "Computer Science Education Week, early December",
  "Register your event any time; December slots at schools fill by October",
  "Web form", "Register an event on hourofcode.com, then offer it to a specific school or library",
  6, 60, "Low", 4,
  "The easiest first outreach event to run. Curriculum is written, free, and translated into dozens of languages. Bring a robot so it is not just a browser tab.",
  ["national","free-materials","december"]),

 ("Girls Who Code", "Start or support a Girls Who Code Club", "https://girlswhocode.com",
  "Equity", "Middle school (6-8)", "Hybrid", "Fall", "Clubs run through the school year; applications open in summer",
  "Club applications typically open mid-year for the following fall",
  "Web form", "Apply to facilitate a club, or offer your team as guest technical mentors to an existing one",
  30, 20, "High", 5,
  "Guest-mentoring an existing club costs far less than starting one and still counts. Ask the facilitator what they need before proposing what you want to teach.",
  ["national","equity","clubs"]),

 ("Boys & Girls Clubs of America", "Club STEM programming", "https://www.bgca.org",
  "Workshop", "Elementary (K-5)", "In person", "Offseason", "Year-round; summer programming is hungriest for volunteers",
  "3-5 weeks; individual clubs decide locally",
  "Email", "Find your local club on bgca.org and email the Program Director directly -- national will just redirect you",
  12, 35, "Medium", 5,
  "Clubs serve the kids least likely to already have a robotics team. Summer is when they most need programming and have the fewest volunteers.",
  ["national","equity","summer"]),

 ("Girl Scouts of the USA", "Robotics badges and Journey support", "https://www.girlscouts.org",
  "Equity", "Elementary (K-5)", "In person", "Winter", "Troop years run September-May; badge days cluster January-March",
  "6-8 weeks through a council; 2-3 weeks for a single troop",
  "Web form", "Contact your regional council's Program department, or ask a troop leader you already know",
  16, 30, "Medium", 5,
  "Girl Scouts has an existing robotics badge structure -- you are helping them earn something specific, which is much easier to say yes to than a generic offer.",
  ["national","equity","badges"]),

 ("Scouting America", "Robotics merit badge and Nova STEM awards", "https://www.scouting.org",
  "Workshop", "Middle school (6-8)", "In person", "Fall", "Troop meetings year-round; merit badge midways in spring and fall",
  "3-4 weeks; merit badge counselors must be registered adults",
  "Email", "Email a local Scoutmaster, or contact the council office about merit badge midway slots",
  10, 25, "Medium", 4,
  "The Robotics merit badge requirements are published and specific. A registered adult mentor must counsel it, but students do the teaching.",
  ["national","badges","scouts"]),

 ("4-H", "4-H STEM and county extension programs", "https://4-h.org",
  "Workshop", "Middle school (6-8)", "In person", "Summer", "Club year runs September-August; fair season peaks July-September",
  "4-6 weeks; county fair exhibits book 4-6 months ahead",
  "Email", "Find your county extension office and email the 4-H Youth Development Agent",
  14, 40, "Medium", 4,
  "The strongest single channel for rural outreach. County agents are paid to connect youth programs and will actively find you an audience.",
  ["national","rural","fairs"]),

 ("Society of Women Engineers", "SWENext and outreach events", "https://swe.org",
  "Equity", "High school (9-12)", "Hybrid", "Winter", "Year-round; Introduce a Girl to Engineering Day in February",
  "6-8 weeks through a professional section",
  "Web form", "Contact your regional SWE section about co-hosting, or register students as SWENext members (free)",
  10, 40, "Low", 5,
  "Co-hosting with a professional SWE section gets you adult engineers on the floor, which is what actually changes a middle schooler's mind.",
  ["national","equity","february"]),

 ("National Society of Black Engineers", "NSBE Jr. chapters", "https://www.nsbe.org",
  "Equity", "High school (9-12)", "Hybrid", "Fall", "Chapter year September-May; national convention in spring",
  "6-10 weeks through a professional chapter",
  "Web form", "Contact your regional NSBE professional chapter about supporting or starting an NSBE Jr. chapter",
  20, 30, "High", 5,
  "Support an existing NSBE Jr. chapter before proposing a new one. Their members often already want robotics and have no equipment.",
  ["national","equity","chapters"]),

 ("SHPE", "Noche de Ciencias family science nights", "https://www.shpe.org",
  "Equity", "Family", "In person", "Fall", "Events run through the school year, concentrated in fall",
  "8-10 weeks through a professional chapter",
  "Web form", "Contact a SHPE professional or student chapter about joining a Noche de Ciencias event",
  12, 100, "Medium", 5,
  "Bilingual family science nights. If your team has Spanish speakers, this is where they are most valuable -- and translated materials count as outreach too.",
  ["national","equity","bilingual"]),

 ("DiscoverE", "Engineers Week and Introduce a Girl to Engineering Day", "https://discovere.org",
  "Equity", "Middle school (6-8)", "Hybrid", "Winter", "Engineers Week is the week of Washington's birthday, late February",
  "Plan 8-10 weeks out; free activity materials available any time",
  "Web form", "Download the free event toolkits and register your event on the DiscoverE site",
  10, 60, "Low", 4,
  "Free, ready-made event kits with a national date attached. The fixed date makes it easy to get a school to commit.",
  ["national","equity","february","free-materials"]),

 ("Association of Science and Technology Centers", "Find a science center near you", "https://www.astc.org",
  "Demo", "Family", "In person", "Offseason", "Year-round; family-science weekends cluster in spring and fall",
  "8-12 weeks -- museums plan public programs far ahead",
  "Web form", "Use the ASTC member directory to find your nearest center, then contact Public Programs",
  16, 400, "Medium", 5,
  "Highest attendance per hour of any venue on this list. They will ask for a certificate of insurance and a load-in plan, so start early.",
  ["national","museums","high-reach"]),

 ("Maker Faire", "Exhibit at a Maker Faire", "https://makerfaire.com",
  "Demo", "All ages", "In person", "Summer", "Faires run spring through fall, dates vary by city",
  "Call for Makers usually closes 8-12 weeks before the event",
  "Web form", "Find your regional faire and submit through its Call for Makers",
  20, 500, "Medium", 4,
  "Apply as a Maker, not a sponsor -- Maker booths are usually free. The crowd is technical and asks real questions, which is good practice for judges.",
  ["national","high-reach","makers"]),

 ("VolunteerMatch", "Search local volunteer needs", "https://www.volunteermatch.org",
  "Community Service", "All ages", "Hybrid", "Offseason", "Year-round, updated continuously",
  "Varies by listing; many are same-week",
  "Web form", "Search by ZIP code and filter to Children & Youth or Education",
  8, 30, "Low", 3,
  "Use this to fill gaps in a slow month. Filter to youth and education so the hours connect to your team's mission rather than being generic service.",
  ["national","search-engine"]),

 ("Idealist", "Search nonprofit volunteer openings", "https://www.idealist.org",
  "Community Service", "All ages", "Hybrid", "Offseason", "Year-round",
  "Varies by listing",
  "Web form", "Search volunteer opportunities by location and cause area",
  8, 30, "Low", 3,
  "Better than VolunteerMatch for finding organizations to partner with long-term rather than one-off shifts.",
  ["national","search-engine"]),

 ("JustServe", "Search community service projects", "https://www.justserve.org",
  "Community Service", "All ages", "In person", "Offseason", "Year-round",
  "Varies; many projects accept same-week signups",
  "Web form", "Search projects by ZIP code; no account needed to browse",
  6, 25, "Low", 3,
  "Strong coverage of small community projects that never make it onto bigger platforms. Useful for filling a weekend.",
  ["national","search-engine"]),

 ("Special Olympics", "Volunteer at local competitions", "https://www.specialolympics.org",
  "Accessibility", "All ages", "In person", "Offseason", "Competitions run year-round by sport and region",
  "3-6 weeks; large games recruit months ahead",
  "Web form", "Find your state or regional program and register as a volunteer",
  10, 60, "Low", 5,
  "Not robotics, and that is fine -- FIRST's Impact Award asks what your team does for the community, not only what it does with robots.",
  ["national","accessibility"]),

 ("Habitat for Humanity", "Volunteer with a local affiliate", "https://www.habitat.org",
  "Community Service", "Adults", "In person", "Offseason", "Build days year-round, weather permitting",
  "2-4 weeks; age minimums vary by affiliate (often 16 for the site, lower for ReStore)",
  "Web form", "Find your local affiliate and register a group through their volunteer page",
  16, 20, "Low", 3,
  "Check the age minimum before you recruit students. ReStore shifts usually accept younger volunteers than the build site does.",
  ["national","service","age-limits"]),

 ("Feeding America", "Volunteer at a member food bank", "https://www.feedingamerica.org",
  "Community Service", "All ages", "In person", "Winter", "Year-round; November-December demand spikes hard",
  "1-3 weeks; holiday shifts fill by October",
  "Web form", "Use the food bank locator, then register your group with that food bank directly",
  12, 40, "Low", 3,
  "The easiest large group activity to book. Sort shifts take 10-20 people at once, which most venues cannot handle.",
  ["national","service","groups"]),

 ("Ronald McDonald House Charities", "Support families near a children's hospital", "https://www.rmhc.org",
  "Community Service", "Family", "In person", "Winter", "Year-round; meal programs run continuously",
  "4-8 weeks; some chapters require an orientation",
  "Web form", "Find your local chapter and ask about group volunteer or Meals-from-the-Heart programs",
  10, 30, "Medium", 4,
  "Cooking a meal for families is a real commitment and reads as genuine rather than performative in an award submission.",
  ["national","service","families"]),

 ("Meals on Wheels America", "Deliver meals with a local program", "https://www.mealsonwheelsamerica.org",
  "Community Service", "Seniors", "In person", "Offseason", "Weekday routes year-round",
  "2-4 weeks; requires a driver and often a background check",
  "Web form", "Find your local program through the site and ask about student volunteers",
  8, 20, "Low", 3,
  "Needs a licensed driver, so this is a mentor-plus-students activity. Routes are short and consistent, which makes recurring hours easy to log.",
  ["national","service","seniors"]),

 ("Science Olympiad", "Volunteer at a regional tournament", "https://www.soinc.org",
  "Volunteering", "Middle school (6-8)", "In person", "Competition", "Invitationals January-February, regionals and states February-April",
  "4-8 weeks; event supervisors recruited earlier",
  "Email", "Contact your state or regional tournament director through the state chapter page",
  10, 150, "Low", 4,
  "Event running and scoring are a natural fit for robotics students and put you in front of hundreds of STEM-interested middle schoolers.",
  ["national","competition","stem"]),

 ("MATHCOUNTS", "Volunteer at a chapter competition", "https://www.mathcounts.org",
  "Volunteering", "Middle school (6-8)", "In person", "Competition", "Chapter competitions in February, state in March",
  "6-8 weeks",
  "Web form", "Contact your chapter coordinator through the MATHCOUNTS volunteer page",
  8, 100, "Low", 3,
  "Proctoring and scoring. Low effort, and it puts your team's name in front of exactly the middle schoolers you want recruiting next year.",
  ["national","competition","february"]),

 ("Destination Imagination", "Volunteer as an appraiser", "https://www.destinationimagination.org",
  "Volunteering", "Elementary (K-5)", "In person", "Competition", "Regional tournaments February-March, Globals in May",
  "6-8 weeks; appraiser training required",
  "Web form", "Find your regional affiliate and register as an appraiser",
  12, 120, "Medium", 3,
  "Requires a short training. Judging creative problem-solving is genuinely good preparation for talking to your own judges.",
  ["national","competition","judging"]),

 ("Technology Student Association", "Support a local TSA chapter", "https://tsaweb.org",
  "Mentoring", "High school (9-12)", "Hybrid", "Winter", "Chapter year runs with the school year; state conferences in spring",
  "6-8 weeks through a chapter advisor",
  "Email", "Contact a chapter advisor at a school with TSA but no robotics team",
  16, 25, "Medium", 4,
  "TSA schools already have a STEM-committed advisor and students. It is the shortest path from 'school with nothing' to 'school with a team'.",
  ["national","chapters","teams"]),

 ("SkillsUSA", "Support a local SkillsUSA chapter", "https://www.skillsusa.org",
  "Mentoring", "High school (9-12)", "In person", "Winter", "Regional and state competitions February-April",
  "6-8 weeks",
  "Email", "Contact a CTE instructor who advises a chapter at a nearby school",
  14, 30, "Medium", 4,
  "CTE programs have machine tools you may not. Partnerships here often run both directions -- you teach controls, they teach machining.",
  ["national","CTE","tools"]),

 ("Project Lead The Way", "Partner with a PLTW school", "https://www.pltw.org",
  "Mentoring", "Middle school (6-8)", "In person", "Fall", "School year; teacher training happens in summer",
  "6-10 weeks through the school",
  "Email", "Find a PLTW school near you and email the engineering pathway teacher",
  12, 60, "Medium", 4,
  "PLTW teachers already run engineering curriculum and are usually short on real hardware. Offer to bring the robot to their classroom.",
  ["national","schools","curriculum"]),

 ("REC Foundation", "Volunteer at a VEX event", "https://www.roboticseducation.org",
  "Volunteering", "Middle school (6-8)", "In person", "Winter", "VEX season runs roughly May-April, events densest November-February",
  "4-6 weeks",
  "Portal", "Register as a volunteer through RobotEvents and pick a local event",
  10, 150, "Low", 3,
  "Yes, it is a different program. Judges notice teams that help the whole robotics ecosystem rather than only their own league.",
  ["competition","cross-program"]),

 ("AbleGamers", "Accessible gaming and adaptive controllers", "https://ablegamers.org",
  "Accessibility", "All ages", "Hybrid", "Offseason", "Year-round",
  "Varies; equipment programs are rolling",
  "Web form", "Read their guidance on accessible play, then contact them about local partnership options",
  14, 15, "High", 5,
  "Pair this with an adaptive-controller build. Their published design guidance keeps you from building something that looks helpful but does not fit anyone.",
  ["national","accessibility","builds"]),

 ("American Library Association", "Find and pitch a public library", "https://www.ala.org",
  "Demo", "All ages", "In person", "Offseason", "Year-round; Summer Reading programming June-August is the biggest opening",
  "4-6 weeks; summer programming is planned by February",
  "Email", "Find your library system's branch list and email the Youth Services or Programming Librarian",
  8, 50, "Low", 4,
  "Libraries are the single most reliable yes on this whole board. Ask in January about summer and you will get a slot; ask in June and you will not.",
  ["libraries","reliable","summer"]),

 ("Girlstart", "Girls in STEM programming and curriculum", "https://girlstart.org",
  "Equity", "Elementary (K-5)", "Hybrid", "Winter", "Programs run through the school year; camps in summer",
  "Varies by program",
  "Web form", "Contact them about program models and free activity resources you can adapt locally",
  10, 40, "Medium", 4,
  "Strongest in Texas but publishes activity designs any team can adapt. Credit them if you use their material.",
  ["equity","curriculum","texas"]),

 ("Black Girls Code", "Support workshops and chapters", "https://wearebgc.org",
  "Equity", "Middle school (6-8)", "Hybrid", "Offseason", "Workshops run through the year in chapter cities",
  "8-12 weeks",
  "Web form", "Check whether they have a chapter in your city, then apply as a volunteer",
  12, 40, "Medium", 5,
  "Chapter cities only. If there is no chapter near you, the honest move is to partner with a local equivalent rather than claim a connection you do not have.",
  ["equity","chapters","workshops"]),

 ("AmeriCorps", "Find service opportunities and partners", "https://americorps.gov",
  "Community Service", "Adults", "Hybrid", "Offseason", "Year-round; service terms start in fall and summer",
  "Varies widely by program",
  "Web form", "Use the site to find local service programs your team can support as volunteers",
  10, 40, "Low", 3,
  "More useful as a way to find organized local partners than as a place your students apply directly.",
  ["national","service","partners"]),

 ("United Way", "Connect with local nonprofits", "https://www.unitedway.org",
  "Community Service", "All ages", "In person", "Fall", "Year-round; Day of Caring events in September",
  "3-6 weeks; Day of Caring registration opens in summer",
  "Web form", "Find your local United Way and ask their volunteer center for youth-appropriate projects",
  10, 50, "Low", 3,
  "Their volunteer center already knows which local nonprofits will say yes to a high school group. Ask them instead of guessing.",
  ["national","service","september"]),

 ("Local library summer reading program", "Book a summer reading slot", "https://www.ala.org",
  "Demo", "Elementary (K-5)", "In person", "Summer", "Programs run June-August; slots are assigned in late winter",
  "Ask in January or February -- by April the schedule is set",
  "Email", "Email the Youth Services Librarian with a specific date range and a one-paragraph description",
  8, 55, "Low", 5,
  "Listed separately from the general library entry because the timing is completely different and teams miss it every single year.",
  ["libraries","summer","timing-critical"]),

 ("FIRST", "Apply for the FIRST Impact Award", "https://www.firstinspires.org",
  "Fundraising", "Adults", "Virtual", "Build season", "Submission window falls in the weeks after Kickoff in January",
  "Check the current season manual -- the deadline is in February and it is hard",
  "Portal", "Submit the essay, executive summary and video through the FIRST dashboard",
  20, 0, "High", 5,
  "This is the award your outreach work is for. Write it from the log you kept all year, not from memory in February. Start the essay in November.",
  ["FIRST","award","deadline"]),

 ("FIRST", "Find your local FIRST Program Delivery Partner", "https://www.firstinspires.org",
  "Mentoring", "Adults", "Hybrid", "Fall", "Useful year-round; most valuable August-October",
  "None -- just email them",
  "Email", "Find your state's Program Delivery Partner on the FIRST site and introduce your team",
  2, 5, "Low", 5,
  "One email. They know every school in your state that wants a team and has no one to help. This is the highest-leverage thirty minutes on this entire board.",
  ["FIRST","high-leverage","start-here"]),

 ("STEM Learning Ecosystems", "Join a regional STEM ecosystem", "https://stemecosystems.org",
  "Community", "All ages", "Hybrid", "Fall", "Ecosystems meet through the year; new members welcomed continuously",
  "Rolling",
  "Web form", "Check whether your region has an ecosystem and ask to join the youth partner network",
  8, 100, "Low", 4,
  "A room with every STEM organization in your region in it. Joining once produces partner leads for years.",
  ["regional","partners","network"]),
]
