"""Real-world vocabularies the outreach pipeline is composed from.

Nothing here is a fabricated listing: metros are real places, target types are
real categories of institution that host robotics outreach, and plays are real
activities FIRST teams run. build.py combines them into prospects, each of which
carries a live search query that finds the actual local contact.
"""

# (metro, state/region code, country, FIRST-ish region grouping)
METROS = [
    ("Boston", "MA", "USA", "Northeast"), ("Worcester", "MA", "USA", "Northeast"),
    ("Providence", "RI", "USA", "Northeast"), ("Hartford", "CT", "USA", "Northeast"),
    ("New Haven", "CT", "USA", "Northeast"), ("Manchester", "NH", "USA", "Northeast"),
    ("Portland", "ME", "USA", "Northeast"), ("Burlington", "VT", "USA", "Northeast"),
    ("New York City", "NY", "USA", "Northeast"), ("Long Island", "NY", "USA", "Northeast"),
    ("Albany", "NY", "USA", "Northeast"), ("Rochester", "NY", "USA", "Northeast"),
    ("Buffalo", "NY", "USA", "Northeast"), ("Syracuse", "NY", "USA", "Northeast"),
    ("Newark", "NJ", "USA", "Northeast"), ("Trenton", "NJ", "USA", "Northeast"),
    ("Philadelphia", "PA", "USA", "Northeast"), ("Pittsburgh", "PA", "USA", "Northeast"),
    ("Harrisburg", "PA", "USA", "Northeast"), ("Wilmington", "DE", "USA", "Northeast"),
    ("Baltimore", "MD", "USA", "Mid-Atlantic"), ("Washington", "DC", "USA", "Mid-Atlantic"),
    ("Richmond", "VA", "USA", "Mid-Atlantic"), ("Virginia Beach", "VA", "USA", "Mid-Atlantic"),
    ("Charleston", "WV", "USA", "Mid-Atlantic"),
    ("Charlotte", "NC", "USA", "Southeast"), ("Raleigh-Durham", "NC", "USA", "Southeast"),
    ("Greensboro", "NC", "USA", "Southeast"), ("Columbia", "SC", "USA", "Southeast"),
    ("Greenville", "SC", "USA", "Southeast"), ("Atlanta", "GA", "USA", "Southeast"),
    ("Savannah", "GA", "USA", "Southeast"), ("Jacksonville", "FL", "USA", "Southeast"),
    ("Orlando", "FL", "USA", "Southeast"), ("Tampa Bay", "FL", "USA", "Southeast"),
    ("Miami", "FL", "USA", "Southeast"), ("Birmingham", "AL", "USA", "Southeast"),
    ("Huntsville", "AL", "USA", "Southeast"), ("Nashville", "TN", "USA", "Southeast"),
    ("Memphis", "TN", "USA", "Southeast"), ("Knoxville", "TN", "USA", "Southeast"),
    ("Louisville", "KY", "USA", "Southeast"), ("Jackson", "MS", "USA", "Southeast"),
    ("New Orleans", "LA", "USA", "Southeast"), ("Baton Rouge", "LA", "USA", "Southeast"),
    ("Little Rock", "AR", "USA", "Southeast"),
    ("Detroit", "MI", "USA", "Great Lakes"), ("Grand Rapids", "MI", "USA", "Great Lakes"),
    ("Lansing", "MI", "USA", "Great Lakes"), ("Cleveland", "OH", "USA", "Great Lakes"),
    ("Columbus", "OH", "USA", "Great Lakes"), ("Cincinnati", "OH", "USA", "Great Lakes"),
    ("Toledo", "OH", "USA", "Great Lakes"), ("Indianapolis", "IN", "USA", "Great Lakes"),
    ("Fort Wayne", "IN", "USA", "Great Lakes"), ("Chicago", "IL", "USA", "Great Lakes"),
    ("Peoria", "IL", "USA", "Great Lakes"), ("Milwaukee", "WI", "USA", "Great Lakes"),
    ("Madison", "WI", "USA", "Great Lakes"), ("Minneapolis-St. Paul", "MN", "USA", "Great Lakes"),
    ("Duluth", "MN", "USA", "Great Lakes"),
    ("St. Louis", "MO", "USA", "Midwest"), ("Kansas City", "MO", "USA", "Midwest"),
    ("Springfield", "MO", "USA", "Midwest"), ("Des Moines", "IA", "USA", "Midwest"),
    ("Cedar Rapids", "IA", "USA", "Midwest"), ("Omaha", "NE", "USA", "Midwest"),
    ("Wichita", "KS", "USA", "Midwest"), ("Sioux Falls", "SD", "USA", "Midwest"),
    ("Fargo", "ND", "USA", "Midwest"),
    ("Dallas-Fort Worth", "TX", "USA", "South Central"), ("Houston", "TX", "USA", "South Central"),
    ("Austin", "TX", "USA", "South Central"), ("San Antonio", "TX", "USA", "South Central"),
    ("El Paso", "TX", "USA", "South Central"), ("Lubbock", "TX", "USA", "South Central"),
    ("Rio Grande Valley", "TX", "USA", "South Central"), ("Oklahoma City", "OK", "USA", "South Central"),
    ("Tulsa", "OK", "USA", "South Central"),
    ("Denver", "CO", "USA", "Mountain"), ("Colorado Springs", "CO", "USA", "Mountain"),
    ("Salt Lake City", "UT", "USA", "Mountain"), ("Boise", "ID", "USA", "Mountain"),
    ("Billings", "MT", "USA", "Mountain"), ("Cheyenne", "WY", "USA", "Mountain"),
    ("Albuquerque", "NM", "USA", "Mountain"), ("Las Cruces", "NM", "USA", "Mountain"),
    ("Phoenix", "AZ", "USA", "Mountain"), ("Tucson", "AZ", "USA", "Mountain"),
    ("Las Vegas", "NV", "USA", "Mountain"), ("Reno", "NV", "USA", "Mountain"),
    ("Los Angeles", "CA", "USA", "Pacific"), ("Orange County", "CA", "USA", "Pacific"),
    ("San Diego", "CA", "USA", "Pacific"), ("Inland Empire", "CA", "USA", "Pacific"),
    ("Bay Area", "CA", "USA", "Pacific"), ("Sacramento", "CA", "USA", "Pacific"),
    ("Fresno", "CA", "USA", "Pacific"), ("Bakersfield", "CA", "USA", "Pacific"),
    ("Portland", "OR", "USA", "Pacific"), ("Eugene", "OR", "USA", "Pacific"),
    ("Seattle", "WA", "USA", "Pacific"), ("Spokane", "WA", "USA", "Pacific"),
    ("Tacoma", "WA", "USA", "Pacific"), ("Anchorage", "AK", "USA", "Pacific"),
    ("Honolulu", "HI", "USA", "Pacific"),
    ("Toronto", "ON", "Canada", "Canada"), ("Ottawa", "ON", "Canada", "Canada"),
    ("Montreal", "QC", "Canada", "Canada"), ("Vancouver", "BC", "Canada", "Canada"),
    ("Calgary", "AB", "Canada", "Canada"), ("Edmonton", "AB", "Canada", "Canada"),
    ("Winnipeg", "MB", "Canada", "Canada"), ("Halifax", "NS", "Canada", "Canada"),
    ("Mexico City", "CDMX", "Mexico", "International"), ("Monterrey", "NL", "Mexico", "International"),
    ("Sao Paulo", "SP", "Brazil", "International"), ("Tel Aviv", "IL", "Israel", "International"),
    ("Istanbul", "TR", "Turkiye", "International"), ("London", "ENG", "United Kingdom", "International"),
    ("Amsterdam", "NH", "Netherlands", "International"), ("Warsaw", "MZ", "Poland", "International"),
    ("Sydney", "NSW", "Australia", "International"), ("Taipei", "TPE", "Chinese Taipei", "International"),
    ("Tokyo", "TK", "Japan", "International"), ("Bengaluru", "KA", "India", "International"),
    ("Springfield", "MA", "USA", "Northeast"), ("New Bedford", "MA", "USA", "Northeast"),
    ("Bridgeport", "CT", "USA", "Northeast"), ("Scranton", "PA", "USA", "Northeast"),
    ("Allentown", "PA", "USA", "Northeast"), ("Erie", "PA", "USA", "Northeast"),
    ("Utica", "NY", "USA", "Northeast"), ("Binghamton", "NY", "USA", "Northeast"),
    ("Atlantic City", "NJ", "USA", "Northeast"), ("Portsmouth", "NH", "USA", "Northeast"),
    ("Frederick", "MD", "USA", "Mid-Atlantic"), ("Salisbury", "MD", "USA", "Mid-Atlantic"),
    ("Roanoke", "VA", "USA", "Mid-Atlantic"), ("Norfolk", "VA", "USA", "Mid-Atlantic"),
    ("Morgantown", "WV", "USA", "Mid-Atlantic"), ("Dover", "DE", "USA", "Mid-Atlantic"),
    ("Asheville", "NC", "USA", "Southeast"), ("Wilmington", "NC", "USA", "Southeast"),
    ("Fayetteville", "NC", "USA", "Southeast"), ("Charleston", "SC", "USA", "Southeast"),
    ("Augusta", "GA", "USA", "Southeast"), ("Macon", "GA", "USA", "Southeast"),
    ("Tallahassee", "FL", "USA", "Southeast"), ("Fort Myers", "FL", "USA", "Southeast"),
    ("Pensacola", "FL", "USA", "Southeast"), ("Gainesville", "FL", "USA", "Southeast"),
    ("Mobile", "AL", "USA", "Southeast"), ("Montgomery", "AL", "USA", "Southeast"),
    ("Chattanooga", "TN", "USA", "Southeast"), ("Bowling Green", "KY", "USA", "Southeast"),
    ("Hattiesburg", "MS", "USA", "Southeast"), ("Shreveport", "LA", "USA", "Southeast"),
    ("Lafayette", "LA", "USA", "Southeast"), ("Fayetteville", "AR", "USA", "Southeast"),
    ("Ann Arbor", "MI", "USA", "Great Lakes"), ("Flint", "MI", "USA", "Great Lakes"),
    ("Kalamazoo", "MI", "USA", "Great Lakes"), ("Akron", "OH", "USA", "Great Lakes"),
    ("Dayton", "OH", "USA", "Great Lakes"), ("Youngstown", "OH", "USA", "Great Lakes"),
    ("South Bend", "IN", "USA", "Great Lakes"), ("Evansville", "IN", "USA", "Great Lakes"),
    ("Rockford", "IL", "USA", "Great Lakes"), ("Champaign-Urbana", "IL", "USA", "Great Lakes"),
    ("Green Bay", "WI", "USA", "Great Lakes"), ("Rochester", "MN", "USA", "Great Lakes"),
    ("Columbia", "MO", "USA", "Midwest"), ("Topeka", "KS", "USA", "Midwest"),
    ("Lincoln", "NE", "USA", "Midwest"), ("Davenport", "IA", "USA", "Midwest"),
    ("Rapid City", "SD", "USA", "Midwest"), ("Bismarck", "ND", "USA", "Midwest"),
    ("Waco", "TX", "USA", "South Central"), ("Corpus Christi", "TX", "USA", "South Central"),
    ("Amarillo", "TX", "USA", "South Central"), ("Beaumont", "TX", "USA", "South Central"),
    ("College Station", "TX", "USA", "South Central"), ("Norman", "OK", "USA", "South Central"),
    ("Fort Collins", "CO", "USA", "Mountain"), ("Pueblo", "CO", "USA", "Mountain"),
    ("Provo", "UT", "USA", "Mountain"), ("Idaho Falls", "ID", "USA", "Mountain"),
    ("Missoula", "MT", "USA", "Mountain"), ("Casper", "WY", "USA", "Mountain"),
    ("Santa Fe", "NM", "USA", "Mountain"), ("Flagstaff", "AZ", "USA", "Mountain"),
    ("Modesto", "CA", "USA", "Pacific"), ("Stockton", "CA", "USA", "Pacific"),
    ("Santa Barbara", "CA", "USA", "Pacific"), ("Salinas", "CA", "USA", "Pacific"),
    ("Redding", "CA", "USA", "Pacific"), ("Bend", "OR", "USA", "Pacific"),
    ("Salem", "OR", "USA", "Pacific"), ("Yakima", "WA", "USA", "Pacific"),
    ("Bellingham", "WA", "USA", "Pacific"), ("Juneau", "AK", "USA", "Pacific"),
    ("Hilo", "HI", "USA", "Pacific"),
    ("Hamilton", "ON", "Canada", "Canada"), ("London", "ON", "Canada", "Canada"),
    ("Quebec City", "QC", "Canada", "Canada"), ("Victoria", "BC", "Canada", "Canada"),
    ("Saskatoon", "SK", "Canada", "Canada"), ("St. John's", "NL", "Canada", "Canada"),
    ("Guadalajara", "JAL", "Mexico", "International"), ("Puebla", "PUE", "Mexico", "International"),
    ("Rio de Janeiro", "RJ", "Brazil", "International"), ("Haifa", "IL", "Israel", "International"),
    ("Ankara", "TR", "Turkiye", "International"), ("Manchester", "ENG", "United Kingdom", "International"),
    ("Rotterdam", "ZH", "Netherlands", "International"), ("Krakow", "MZ", "Poland", "International"),
    ("Melbourne", "VIC", "Australia", "International"), ("Kaohsiung", "KHH", "Chinese Taipei", "International"),
    ("Osaka", "OS", "Japan", "International"), ("Mumbai", "MH", "India", "International"),
    ("Seoul", "SEO", "South Korea", "International"), ("Singapore", "SG", "Singapore", "International"),
]

# key, label, contact role to ask for, how you get in, typical lead time
TARGETS = [
    ("library",    "Public library branch",              "Youth Services / Programming Librarian", "Email", "4-6 weeks"),
    ("elem",       "Elementary school",                  "Principal or STEM/Science lead",         "Email", "4-8 weeks"),
    ("middle",     "Middle school",                      "Science department chair",               "Email", "4-8 weeks"),
    ("highschool", "High school without a team",         "Counselor or CTE coordinator",           "Email", "6-10 weeks"),
    ("museum",     "Science center or children's museum","Education / Public Programs Manager",    "Web form", "8-12 weeks"),
    ("bgc",        "Boys & Girls Club",                  "Program Director",                       "Email", "3-5 weeks"),
    ("ymca",       "YMCA branch",                        "Youth Development Director",             "Email", "3-5 weeks"),
    ("gs",         "Girl Scouts council or troop",       "Council Program Manager",                "Web form", "6-8 weeks"),
    ("scouts",     "Scouting America troop or pack",     "Scoutmaster or Cubmaster",               "Email", "3-4 weeks"),
    ("fourh",      "4-H club or county extension",       "County 4-H Youth Development Agent",     "Email", "4-6 weeks"),
    ("hospital",   "Children's hospital",                "Child Life Services",                    "Web form", "10-14 weeks"),
    ("senior",     "Senior center or retirement community", "Activities Director",                 "Phone", "2-4 weeks"),
    ("parks",      "Parks & recreation department",      "Recreation Program Coordinator",         "Web form", "6-8 weeks"),
    ("cc",         "Community college",                  "STEM outreach or dual-enrollment office","Email", "6-8 weeks"),
    ("univ",       "University engineering outreach office", "K-12 Outreach Coordinator",          "Web form", "8-12 weeks"),
    ("maker",      "Makerspace or hackerspace",          "Shop lead or board member",              "Email", "2-3 weeks"),
    ("fair",       "County or state fair",               "Exhibits / Vendor Coordinator",          "Web form", "16-24 weeks"),
    ("market",     "Farmers market",                     "Market Manager",                         "Email", "3-4 weeks"),
    ("city",       "City council or mayor's office",     "Constituent Services or Chief of Staff", "Email", "6-10 weeks"),
    ("chamber",    "Chamber of commerce",                "Membership or Events Director",          "Email", "4-6 weeks"),
    ("rotary",     "Rotary, Kiwanis or Lions club",      "Program Chair",                          "Email", "3-6 weeks"),
    ("manuf",      "Local manufacturer or machine shop", "Plant Manager or HR / Community Relations", "Email", "6-10 weeks"),
    ("tech",       "Local tech employer",                "University Relations or CSR lead",       "Email", "8-12 weeks"),
    ("faith",      "Faith community youth group",        "Youth Minister or Director",             "Email", "3-5 weeks"),
    ("refugee",    "Refugee resettlement or ESL program","Youth Program Coordinator",              "Email", "4-8 weeks"),
    ("sped",       "Special education program",          "Director of Special Services",           "Email", "8-12 weeks"),
    ("dhh",        "School for the deaf or blind",       "Outreach / Transition Coordinator",      "Email", "10-14 weeks"),
    ("title1",     "Title I school district",            "Federal Programs Coordinator",           "Email", "8-12 weeks"),
    ("homeschool", "Homeschool co-op",                   "Co-op Enrichment Coordinator",           "Email", "3-5 weeks"),
    ("afterschool","After-school program (21st CCLC)",   "Site Coordinator",                       "Email", "4-6 weeks"),
    ("media",      "Local news or public radio station", "Assignment Desk or Community Editor",    "Email", "2-4 weeks"),
    ("foodbank",   "Food bank or pantry",                "Volunteer Coordinator",                  "Web form", "1-3 weeks"),
    ("shelter",    "Animal shelter",                     "Volunteer Manager",                      "Web form", "1-3 weeks"),
    ("habitat",    "Habitat for Humanity affiliate",     "Volunteer Services",                     "Web form", "2-4 weeks"),
    ("tribal",     "Tribal youth or Native education program", "Education Director",               "Phone", "8-12 weeks"),
    ("military",   "Military base youth program",        "School Liaison Officer",                 "Email", "8-12 weeks"),
    ("juvenile",   "Juvenile justice education program", "Education Administrator",                "Phone", "12-16 weeks"),
    ("housing",    "Public housing community center",    "Resident Services Coordinator",          "Phone", "4-6 weeks"),
    ("rural",      "Rural school district",              "Superintendent (small districts answer)","Email", "6-10 weeks"),
    ("bilingual",  "Dual-language or bilingual school",  "Bilingual Programs Coordinator",         "Email", "6-8 weeks"),
    ("fll",        "Nearby FLL or FTC team",             "Head Coach",                             "Email", "2-4 weeks"),
    ("event",      "Regional FIRST event",               "Volunteer Coordinator",                  "Portal", "6-8 weeks"),
    ("camp",       "Summer camp or day camp",            "Camp Director",                          "Email", "12-20 weeks"),
    ("shelterfam", "Family or transitional housing shelter", "Family Services Director",           "Phone", "4-8 weeks"),
]


# Activities FIRST teams actually run. Fields:
# key, name, category, audience, format, duration, hours, reach, effort,
# impact(1-5), season, cost, compatible target keys, what you need, what to bring
PLAYS = [
    ("demo", "Robot demo and drive-it-yourself", "Demo", "All ages", "In person",
     "2 hours", 8, 60, "Low", 4, "Offseason", "$0",
     ["library","bgc","ymca","market","fair","senior","parks","faith","housing","chamber","rotary","museum","homeschool","shelterfam","refugee"],
     ["Working robot or a driveable offseason bot", "Battery cart and a charged spare", "Two students who can explain the drivetrain without jargon"],
     ["Safety glasses for guests", "Bumper-height barrier or cones", "Extension cord and power strip", "Team banner", "Sign-up clipboard for emails"]),

    ("build", "Hands-on build workshop", "Workshop", "Elementary (K-5)", "In person",
     "90 minutes", 12, 25, "Medium", 5, "Offseason", "$40-80 materials",
     ["library","elem","bgc","ymca","afterschool","homeschool","housing","fourh","camp","title1","refugee","bilingual"],
     ["One kit per 2 students", "1 mentor per 8 kids", "Tables, not desks"],
     ["Pre-sorted parts in labeled bags", "A finished example to show", "Spare batteries", "Photo release forms"]),

    ("fllmentor", "Mentor a rookie FLL team", "Mentoring", "Elementary (K-5)", "Hybrid",
     "2 hrs/week for 10 weeks", 24, 12, "High", 5, "Fall", "$0",
     ["elem","middle","library","bgc","afterschool","fourh","homeschool","title1","rural","housing","faith"],
     ["Two students committed for the full season", "Background-check policy checked with the host", "Coach who owns scheduling"],
     ["Your own team's build log to show", "A mission-strategy worksheet", "Patience for the robot game rules"]),

    ("ftcmentor", "Mentor a rookie FTC or FRC team", "Mentoring", "Middle school (6-8)", "Hybrid",
     "3 hrs/week in season", 40, 15, "High", 5, "Build season", "$0",
     ["middle","highschool","fll","cc","rural","title1","military","tribal"],
     ["Students who have survived one full build season", "Clear line on what you will not do for them"],
     ["CAD files you are willing to share", "Your wiring diagram", "A list of your own rookie-year mistakes"]),

    ("judge", "Volunteer at an FLL or FTC qualifier", "Volunteering", "All ages", "In person",
     "Full day", 10, 200, "Low", 4, "Competition", "$0",
     ["event","fll","cc","univ","museum"],
     ["Volunteer registration and screening completed in advance", "Closed-toe shoes"],
     ["Water bottle", "Snacks", "A book for the slow rounds"]),

    ("girlsday", "Girls in STEM day", "Equity", "Middle school (6-8)", "In person",
     "3 hours", 20, 45, "Medium", 5, "Winter", "$60-150",
     ["gs","library","middle","bgc","ymca","univ","cc","museum","title1","bilingual","housing"],
     ["Women mentors and alumnae on the floor, not just on a slide", "Activity that ends in something they keep"],
     ["Take-home kits", "Alumnae contact cards", "Name tags with first names only"]),

    ("cad", "Intro to CAD session", "Workshop", "High school (9-12)", "Hybrid",
     "2 hours", 10, 20, "Medium", 4, "Offseason", "$0",
     ["middle","highschool","library","cc","maker","homeschool","rural","afterschool","military"],
     ["A computer lab or laptops", "Free accounts set up before the session, not during"],
     ["A part file that prints in 20 minutes", "Printed step-by-step handout", "USB drive with the software installer"]),

    ("code", "Beginner programming class", "Workshop", "Elementary (K-5)", "Hybrid",
     "1 hour", 6, 25, "Low", 4, "Winter", "$0",
     ["library","elem","middle","bgc","afterschool","housing","refugee","bilingual","title1","fourh","juvenile"],
     ["Devices with a browser", "An unplugged backup for when the wifi dies"],
     ["Printed Hour of Code cards", "Stickers", "A robot to show what the code eventually drives"]),

    ("print3d", "3D printing demo", "Demo", "All ages", "In person",
     "2 hours", 8, 50, "Low", 3, "Offseason", "$15-30 filament",
     ["library","maker","fair","market","museum","chamber","senior","cc","homeschool","manuf"],
     ["A printer that survives transport", "A print that finishes inside the session"],
     ["Failed prints (people love these)", "A benchy and a printed gear train", "Filament samples to hand out"]),

    ("panel", "Career talk or classroom visit", "Speaking", "High school (9-12)", "Hybrid",
     "50 minutes", 5, 90, "Low", 3, "Fall", "$0",
     ["middle","highschool","cc","rotary","chamber","faith","juvenile","military","tribal","rural","refugee"],
     ["Students who can talk about failure, not just trophies", "A slide count under 12"],
     ["One physical part to pass around", "Team business cards", "The QR code for your team site"]),

    ("pettingzoo", "Robot petting zoo at a public event", "Demo", "All ages", "In person",
     "4 hours", 16, 300, "Medium", 4, "Offseason", "$0",
     ["fair","market","museum","city","parks","chamber","library","faith"],
     ["Booth space and a load-in time", "A driver rotation so nobody burns out", "Certificate of insurance if the venue asks"],
     ["10x10 canopy and weights", "Zip ties, gaffer tape, spare fuses", "Two tables and a trash bin", "Cash box only if you are selling"]),

    ("parade", "Parade entry with the robot", "Community", "All ages", "In person",
     "Half day", 12, 500, "Medium", 3, "Summer", "$0-50 entry",
     ["city","parks","chamber","fair","faith","rotary"],
     ["A trailer or a cart that survives 2 miles", "Walkers who hand out flyers"],
     ["Flyers with your recruiting QR code", "Water for the walkers", "A tow plan for when the battery dies"]),

    ("gobabygo", "Adapt a ride-on car for a child with limited mobility", "Accessibility", "Family", "In person",
     "Full day build", 30, 4, "High", 5, "Offseason", "$150-300 per car",
     ["hospital","sped","dhh","univ","habitat","parks","shelterfam","fourh"],
     ["A physical or occupational therapist signing off on the fit", "A specific child, measured, not a generic build"],
     ["Ride-on car, PVC, pool noodles, big arcade button", "Soldering station", "Seatbelt hardware rated for the child's size"]),

    ("toyadapt", "Switch-adapt toys for kids with disabilities", "Accessibility", "Family", "In person",
     "3 hours", 12, 20, "Medium", 5, "Winter", "$10-20 per toy",
     ["hospital","sped","dhh","library","maker","univ","shelterfam","faith"],
     ["Soldering irons and ventilation", "Toys bought new, in the box"],
     ["3.5mm mono jacks and wire", "Heat-shrink and a heat gun", "Small screwdrivers", "A tested example toy"]),

    ("safety", "Shop safety and tool basics", "Workshop", "High school (9-12)", "In person",
     "90 minutes", 6, 25, "Low", 3, "Fall", "$0",
     ["highschool","cc","maker","manuf","scouts","fourh","juvenile","military"],
     ["Real PPE for everyone in the room", "A tool you are genuinely qualified to teach"],
     ["Safety glasses in a bin", "A cut-off drill bit and a chewed-up piece of stock", "Your team's safety manual"]),

    ("sponsor", "Sponsorship pitch and shop tour", "Fundraising", "Adults", "In person",
     "45 minutes", 8, 6, "Medium", 5, "Fall", "$0",
     ["manuf","tech","chamber","rotary","city","cc","univ","media"],
     ["A one-page budget that shows where the money goes", "Two students who lead the meeting, not the mentor", "A tiered sponsorship sheet"],
     ["Printed one-pager and last year's impact numbers", "A part the robot actually uses", "A thank-you plan in writing"]),

    ("camp", "Run a summer camp session", "Camp", "Elementary (K-5)", "In person",
     "Week-long, 3 hrs/day", 45, 30, "High", 5, "Summer", "$200-500 materials",
     ["camp","parks","library","bgc","ymca","museum","cc","fourh","title1","housing"],
     ["Adult supervision ratios that meet the host's policy", "A curriculum written down before June", "Registration handled by the host, not you"],
     ["Kits for every day plus 20% spares", "Nametags and a roster", "A rainy-day indoor plan", "Snacks cleared for allergies"]),

    ("familynight", "Family STEM night", "Community", "Family", "In person",
     "2 hours", 14, 120, "Medium", 4, "Winter", "$50-120",
     ["elem","middle","library","title1","bilingual","refugee","housing","faith","homeschool","afterschool"],
     ["Stations that run without a facilitator lecturing", "Materials in the languages families actually speak"],
     ["6-8 station kits", "Passport cards kids get stamped", "Translated instructions", "A raffle prize"]),

    ("scrimmage", "Host an offseason scrimmage", "Competition", "High school (9-12)", "In person",
     "Full day", 40, 150, "High", 4, "Summer", "$300-800",
     ["highschool","cc","univ","event","parks","museum"],
     ["A gym or field house booked months out", "Field elements borrowed or built", "An FTA-type volunteer who knows the control system"],
     ["Field elements and scoring materials", "Extension cords and a network switch", "Pit tables", "Lunch plan for 100+ people"]),

    ("cleanup", "Community service day (food, shelter, trail)", "Community Service", "All ages", "In person",
     "4 hours", 16, 40, "Low", 3, "Offseason", "$0",
     ["foodbank","shelter","habitat","parks","faith","city","shelterfam","housing"],
     ["Signed waivers for minors", "Transportation sorted before you commit"],
     ["Work gloves", "Team shirts so you are visible", "A photographer for the sponsor report"]),

    ("translate", "Translate STEM materials into another language", "Equity", "Family", "Virtual",
     "6 hours", 6, 200, "Low", 4, "Winter", "$0",
     ["bilingual","refugee","library","title1","housing","tribal","homeschool"],
     ["A native speaker reviewing, not just a translation tool", "Permission from whoever owns the original"],
     ["Editable source files", "A glossary of the technical terms", "A native-speaker reviewer's name in the credits"]),

    ("seniortech", "Tech help session for seniors", "Community", "Seniors", "In person",
     "2 hours", 8, 25, "Low", 3, "Winter", "$0",
     ["senior","library","faith","housing","parks"],
     ["Patience and a slow talking speed", "One student per two guests"],
     ["Printed large-type handouts", "A magnifier", "A robot to show at the end so it is not all phone settings"]),

    ("startteam", "Help a school start its own team", "Mentoring", "Middle school (6-8)", "Hybrid",
     "Ongoing, 20+ hrs", 40, 20, "High", 5, "Fall", "$0",
     ["elem","middle","highschool","rural","title1","tribal","military","refugee","homeschool","cc"],
     ["A committed adult at the host school (without one, it dies)", "A realistic first-year budget", "A grant deadline you have actually checked"],
     ["Your startup checklist", "Rookie grant application links", "A list of your local suppliers", "An offer to house their build if they have no space"]),

    ("press", "Local media story about the team", "Outreach Media", "Adults", "Hybrid",
     "3 hours", 4, 2000, "Low", 3, "Competition", "$0",
     ["media","city","chamber","library","museum"],
     ["An actual news hook: a deadline, a win, a kid's story", "A parent's permission for any student named"],
     ["A one-paragraph pitch, not a press release", "Two good photos already taken", "A student who is comfortable on camera"]),

    ("grant", "Apply for an outreach or STEM grant", "Fundraising", "Adults", "Virtual",
     "8 hours", 10, 0, "Medium", 4, "Fall", "$0",
     ["manuf","tech","city","univ","chamber","rotary","fourh","title1"],
     ["Your team's 501(c)(3) or your school's tax ID", "Last year's outreach numbers, counted honestly"],
     ["Budget spreadsheet", "Two paragraphs on impact with real numbers", "A mentor who proofreads before submit"]),

    ("hospitalvisit", "Robot visit to a pediatric ward", "Accessibility", "Family", "In person",
     "2 hours", 10, 30, "High", 5, "Winter", "$0",
     ["hospital","shelterfam","sped"],
     ["Infection-control clearance and a wiped-down robot", "Child Life staff leading, you following", "No photos unless staff arranges it"],
     ["A small, quiet, slow robot", "Hand sanitizer", "Something each child keeps", "A backup plan if a room is closed"]),

    ("toolkit", "Donate tools or build space to a rookie team", "Community Service", "High school (9-12)", "In person",
     "4 hours", 8, 15, "Low", 4, "Summer", "$0-200",
     ["fll","rural","title1","tribal","military","maker","cc","housing"],
     ["An inventory of what you actually have spare", "Their space measured before you deliver"],
     ["Labeled, working tools (not broken ones)", "A written list of what you gave", "An offer to show them how to use it"]),

    ("boothfair", "Recruiting booth at a school or club fair", "Community", "Middle school (6-8)", "In person",
     "3 hours", 9, 200, "Low", 4, "Fall", "$0-40 printing",
     ["middle","highschool","elem","cc","library","chamber","homeschool","military"],
     ["Table assignment confirmed in writing", "Students who talk to people instead of each other"],
     ["Sign-up sheet or QR form", "A driveable robot or at least a subassembly", "Candy (it works)", "Team flyers"]),

    ("workshopseries", "Multi-week after-school robotics club", "Workshop", "Middle school (6-8)", "In person",
     "6 weeks, 90 min/week", 30, 20, "High", 5, "Winter", "$150-400",
     ["afterschool","middle","elem","bgc","ymca","library","title1","housing","juvenile","refugee"],
     ["The same students every week (get the host to lock the roster)", "A curriculum that survives a missed week"],
     ["A kit per pair that stays at the site", "Attendance sheet", "A final showcase date on the calendar"]),

    ("adaptivecontrol", "Build an adaptive game controller", "Accessibility", "All ages", "In person",
     "4 hours", 14, 10, "High", 5, "Offseason", "$60-120 each",
     ["hospital","sped","dhh","maker","univ","library","shelterfam"],
     ["The specific user's needs documented first", "Someone who can test-fit it with the user"],
     ["Switch jacks, buttons, enclosure", "Soldering and 3D-printed mounts", "A follow-up visit scheduled to fix the fit"]),

    ("teachercpd", "Run a workshop for teachers", "Workshop", "Adults", "Hybrid",
     "3 hours", 12, 30, "Medium", 5, "Summer", "$0-100",
     ["elem","middle","highschool","title1","rural","cc","univ","bilingual","tribal"],
     ["Coordination with the district PD calendar (they plan a year out)", "Materials they can reuse without you"],
     ["A printed lesson plan aligned to their standards", "A parts list with prices and links", "Your email for the follow-up questions"]),
]

SEASON_ORDER = ["Build season", "Competition", "Offseason", "Summer", "Fall", "Winter"]
SEASON_MONTHS = {
    "Build season": "January - February",
    "Competition":  "February - April",
    "Offseason":    "May - August",
    "Summer":       "June - August",
    "Fall":         "September - November",
    "Winter":       "December - February",
}
