import type { Provenance, Source } from '@/domain/types';
import { Icon } from './Icon';
import { Tooltip } from './primitives';

/* ==========================================================================
   Data reliability surface — sections 40 and 41.
   Verified, AI-generated, user-entered and demo data never look alike, and
   every factual claim carries its source and verification date.
   ========================================================================== */

const LABEL: Record<Provenance['kind'], string> = {
  verified: 'Verified',
  ai: 'AI guidance',
  user: 'You entered this',
  demo: 'Demo data',
  unverified: 'Unverified',
};

const EXPLANATION: Record<Provenance['kind'], string> = {
  verified: 'Taken from an official source and checked on the date shown.',
  ai: 'Generated by Pathway AI from your profile. Guidance, not fact — and not a substitute for your counselor or an official source.',
  user: 'This is what you told us. We do not change or infer around it.',
  demo: 'Realistic placeholder data written for development. It has NOT been verified against the institution and should not be relied on. Check the official source before acting on it.',
  unverified: 'Summarised from public descriptions but not re-checked against the publisher this cycle. Confirm current details at the source.',
};

export function ProvenanceChip({ provenance, compact }: { provenance: Provenance; compact?: boolean }) {
  const tip = [EXPLANATION[provenance.kind], provenance.note, provenance.lastVerified ? `Last verified ${provenance.lastVerified}.` : null]
    .filter(Boolean)
    .join(' ');
  return (
    <Tooltip label={tip}>
      <span className={`prov prov-${provenance.kind}`} tabIndex={0}>
        {compact ? LABEL[provenance.kind].split(' ')[0] : LABEL[provenance.kind]}
        {provenance.lastVerified && !compact ? ` · ${provenance.lastVerified}` : null}
      </span>
    </Tooltip>
  );
}

export function SourceList({ sources, className = '' }: { sources?: Source[]; className?: string }) {
  if (!sources?.length) {
    return <p className={`t-2xs faint ${className}`}>No source recorded for this.</p>;
  }
  return (
    <ul className={`t-2xs subtle col g-1 ${className}`}>
      {sources.map((s, i) => (
        <li key={i} className="row g-1">
          <Icon name="link" size={11} />
          {s.url ? (
            <a href={s.url} target="_blank" rel="noreferrer noopener" className="row g-1">
              {s.label}
              {s.publisher ? ` — ${s.publisher}` : ''}
              <Icon name="external" size={10} />
            </a>
          ) : (
            <span>
              {s.label}
              {s.publisher ? ` — ${s.publisher}` : ''}
            </span>
          )}
        </li>
      ))}
    </ul>
  );
}

export function ProvenanceFooter({ provenance, className = '' }: { provenance: Provenance; className?: string }) {
  return (
    <div className={`col g-2 ${className}`}>
      <div className="row g-2 wrap">
        <ProvenanceChip provenance={provenance} />
        {provenance.lastVerified ? <span className="t-2xs faint">Last verified {provenance.lastVerified}</span> : null}
      </div>
      {provenance.note ? <p className="t-2xs faint">{provenance.note}</p> : null}
      <SourceList sources={provenance.sources} />
    </div>
  );
}

/** The persistent banner shown wherever catalog figures appear. */
export function DemoDataBanner({ what = 'The figures on this page' }: { what?: string }) {
  return (
    <div className="notice notice-warn mb-4">
      <Icon name="alert" size={16} className="notice-icon" />
      <div>
        <strong>{what} are demo data.</strong> They are realistic and internally consistent, but they have not been verified
        against any institution and must not be relied on for decisions. Every record links to its official source — check there
        before you act on anything.
      </div>
    </div>
  );
}

/** Shown above anything the engine produced, so guidance never reads as fact. */
export function AIGuidanceNote({ children }: { children?: React.ReactNode }) {
  return (
    <div className="notice notice-ai">
      <Icon name="sparkles" size={16} className="notice-icon" />
      <div>
        {children ?? (
          <>
            <strong>This is AI guidance, not fact.</strong> It is generated from your profile using the same engine as the rest
            of the app. It cannot predict admission decisions and does not replace your school counselor.
          </>
        )}
      </div>
    </div>
  );
}
