import type { Explanation, FitBand, RecommendationPriority } from '@/domain/types';

/**
 * Section 43: every recommendation answers why this, why now, how it connects,
 * what it requires, and what the alternatives are — plus what we do not know.
 *
 * Fields left out come back as empty rather than invented, so a caller can never
 * accidentally publish a confident-sounding reason the engine did not produce.
 */
export function explanation(input: Partial<Explanation> & Pick<Explanation, 'whyThis'>): Explanation {
  return {
    whyNow: '',
    connection: '',
    requires: '',
    alternatives: [],
    evidence: [],
    ...input,
  };
}

export function bandFromScore(score: number): FitBand {
  if (score >= 78) return 'strong';
  if (score >= 62) return 'good';
  if (score >= 44) return 'moderate';
  if (score >= 22) return 'limited';
  return 'unclear';
}

export const BAND_LABEL: Record<FitBand, string> = {
  strong: 'Strong fit',
  good: 'Good fit',
  moderate: 'Moderate fit',
  limited: 'Limited fit',
  unclear: 'Not enough information',
};

export const BAND_TONE: Record<FitBand, 'ok' | 'accent' | 'warn' | 'danger' | 'default'> = {
  strong: 'ok',
  good: 'accent',
  moderate: 'warn',
  limited: 'danger',
  unclear: 'default',
};

export const PRIORITY_LABEL: Record<RecommendationPriority, string> = {
  important: 'Important',
  useful: 'Useful',
  optional: 'Optional',
};

export const PRIORITY_TONE: Record<RecommendationPriority, 'danger' | 'warn' | 'default'> = {
  important: 'danger',
  useful: 'warn',
  optional: 'default',
};

/**
 * The single sentence attached to every selectivity figure in the product.
 * Section 5: fit is not admission probability, and we never blur that.
 */
export const FIT_DISCLAIMER =
  'Fit is not an admission chance. These figures describe how a college matches what you have told us, and how your preparation compares to the students it has admitted before — not your likelihood of being admitted.';

export const AI_GUIDANCE_NOTE =
  'Generated by Pathway AI from your profile. It is guidance, not fact, and it does not replace your counselor or official sources.';
