#!/usr/bin/env node
/**
 * Build the single-file browser edition.
 *
 * The trick is that almost nothing is rewritten. The whole product — the
 * learning engine, the API routes, the views, the charts — is the same source
 * the server runs. Only the handful of modules that genuinely need a server
 * (storage, the model client, the filesystem, Express) are swapped for browser
 * implementations, and then every module is embedded in one HTML file and
 * wired together with an import map over blob URLs, which preserves real ES
 * module semantics rather than concatenating everything into one scope.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const rel = (file) => path.relative(ROOT, file).split(path.sep).join('/');
const read = (file) => fs.readFileSync(file, 'utf8');

const ENTRY = path.join(ROOT, 'browser/main.js');
const OUT = path.join(ROOT, 'axiom.html');

/** Modules that mean something different without a server behind them. */
const SUBSTITUTIONS = {
  'server/config.js': 'browser/config.js',
  'server/store.js': 'browser/store.js',
  'server/prompts.js': 'browser/prompts.js',
  'server/util/ids.js': 'browser/ids.js',
  'server/engine/sources.js': 'browser/sources.js',
  'server/llm/anthropic.js': 'browser/anthropic.js',
  'server/llm/index.js': 'browser/llm.js',
  'server/routes/files.js': 'browser/files.js',
  express: 'browser/express.js',
};

/* ------------------------------------------------------------------ prompts */

function writePromptData() {
  const dir = path.join(ROOT, 'server/prompts');
  const prompts = {};
  for (const file of fs.readdirSync(dir).sort()) {
    if (file.endsWith('.md')) prompts[file.replace(/\.md$/, '')] = read(path.join(dir, file));
  }
  const body = `/* Generated by build.mjs from server/prompts/*.md — do not edit by hand. */\nexport const PROMPTS = ${JSON.stringify(prompts, null, 2)};\n`;
  const target = path.join(ROOT, 'browser/prompt-data.js');
  const existing = fs.existsSync(target) ? read(target) : null;
  if (existing !== body) fs.writeFileSync(target, body);
  return Object.keys(prompts).length;
}

/* ------------------------------------------------------------ module graph */

const SPECIFIER = /(\bfrom\s*|\bimport\s*\(\s*)(['"])([^'"\n]+)\2/g;

function resolveSpecifier(specifier, fromFile) {
  const substituted = SUBSTITUTIONS[specifier];
  if (substituted) return path.join(ROOT, substituted);

  if (!specifier.startsWith('.')) {
    throw new Error(`${rel(fromFile)} imports "${specifier}", which has no browser substitute.`);
  }
  const resolved = path.resolve(path.dirname(fromFile), specifier);
  const id = rel(resolved);
  return SUBSTITUTIONS[id] ? path.join(ROOT, SUBSTITUTIONS[id]) : resolved;
}

function collect(entry) {
  const modules = new Map();
  const queue = [entry];

  while (queue.length) {
    const file = queue.shift();
    const id = rel(file);
    if (modules.has(id)) continue;
    if (!fs.existsSync(file)) throw new Error(`missing module: ${id}`);

    const source = read(file).replace(SPECIFIER, (whole, lead, quote, specifier) => {
      if (!specifier.startsWith('.') && !SUBSTITUTIONS[specifier]) return whole;
      const target = resolveSpecifier(specifier, file);
      queue.push(target);
      return `${lead}${quote}axiom:${rel(target)}${quote}`;
    });

    modules.set(id, source);
  }
  return modules;
}

/* --------------------------------------------------------------------- html */

const escapeForScript = (text) => text.replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--');

function buildHtml(modules, css) {
  const sources = Object.fromEntries([...modules].map(([id, src]) => [`axiom:${id}`, src]));
  const shell = read(path.join(ROOT, 'public/index.html'));
  const head = shell.slice(shell.indexOf('<head>') + 6, shell.indexOf('</head>'));

  // Keep the shell's metadata and CDN links, drop the file references that only
  // make sense when something is serving a directory.
  const meta = head
    .split('\n')
    .filter((line) => !line.includes('href="/styles.css"'))
    .join('\n')
    .trim();

  return `<!doctype html>
<html lang="en" data-theme="dark">
<head>
${meta}
<style>
${css}
</style>
</head>
<body>
<div id="app" class="app">
  <div class="boot">
    <div class="boot-mark"></div>
    <p>Starting Axiom…</p>
  </div>
</div>
<noscript><p style="padding:40px;font:15px system-ui">Axiom needs JavaScript to run.</p></noscript>
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous" defer></script>
<script id="axiom-modules" type="application/json">
${escapeForScript(JSON.stringify(sources))}
</script>
<script>
/* Wire the embedded modules together as real ES modules: each becomes a blob
   URL, and an import map resolves the "axiom:" specifiers between them. This
   keeps module scope, live bindings and cycles working exactly as they do when
   the same files are served over HTTP. */
(function () {
  var sources = JSON.parse(document.getElementById('axiom-modules').textContent);
  var imports = {};
  try {
    for (var id in sources) {
      imports[id] = URL.createObjectURL(new Blob([sources[id]], { type: 'text/javascript' }));
    }
  } catch (err) {
    document.getElementById('app').innerHTML =
      '<div style="padding:48px;font:15px/1.6 system-ui;max-width:60ch;margin:0 auto">' +
      '<h1 style="font-size:22px">This browser cannot start Axiom</h1>' +
      '<p>It blocked the object URLs the app is assembled from. Try Chrome, Edge, Firefox or Safari with default settings.</p></div>';
    return;
  }

  var map = document.createElement('script');
  map.type = 'importmap';
  map.textContent = JSON.stringify({ imports: imports });
  document.head.appendChild(map);

  var boot = document.createElement('script');
  boot.type = 'module';
  boot.textContent = 'import "axiom:browser/main.js";';
  document.head.appendChild(boot);

  window.addEventListener('error', function (event) {
    if (document.querySelector('.gate') || document.querySelector('.shell')) return;
    var app = document.getElementById('app');
    if (app && app.querySelector('.boot')) {
      app.innerHTML =
        '<div style="padding:48px;font:15px/1.6 system-ui;max-width:60ch;margin:0 auto">' +
        '<h1 style="font-size:22px">Axiom failed to start</h1><pre style="white-space:pre-wrap;opacity:.7">' +
        String(event.message || event.error) + '</pre></div>';
    }
  });
})();
</script>
</body>
</html>
`;
}

/* --------------------------------------------------------------------- main */

const promptCount = writePromptData();
const modules = collect(ENTRY);
const css = read(path.join(ROOT, 'public/styles.css'));
const html = buildHtml(modules, css);
fs.writeFileSync(OUT, html);

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
console.log(`axiom.html  ${kb(Buffer.byteLength(html))}`);
console.log(`  ${modules.size} modules · ${promptCount} prompts · ${kb(Buffer.byteLength(css))} of CSS`);
const substituted = [...modules.keys()].filter((id) => id.startsWith('browser/'));
console.log(`  browser implementations: ${substituted.map((s) => s.replace('browser/', '')).join(', ')}`);
